spring.application.name=springboot-jooq-employee-crud

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=waction
spring.datasource.password=w@ct10n

jooq.sql-dialect=POSTGRES
